const fs = require('fs');
function write(rel, content) { fs.writeFileSync(rel, content, 'utf8'); console.log('wrote', rel, content.length); }

const HONESTY_IMPL = [
"// tests/_honesty_impl.mjs",
"// Pure logic mirror of src/lib/honesty.ts.",
"",
"export const PARTIAL_THRESHOLD = 0.40;",
"",
"export function ratioFor(route) {",
"  const v = route && route.validation;",
"  if (!v || !v.total) return 0;",
"  if (typeof v.degradedSteps !== 'number') return 0;",
"  return v.degradedSteps / v.total;",
"}",
"",
"export function computeHonestyAssessment(routes) {",
"  if (!routes || routes.length === 0) {",
"    return { level: 'confiable', label: 'Sin rutas', worstRatio: 0, totalDegraded: 0 };",
"  }",
"  let worst = 0;",
"  let totalDeg = 0;",
"  for (const r of routes) {",
"    const ratio = ratioFor(r);",
"    if (ratio > worst) worst = ratio;",
"    totalDeg += ((r && r.validation && r.validation.degradedSteps) || 0);",
"  }",
"  let level;",
"  let label;",
"  if (worst === 0) {",
"    level = 'confiable';",
"    label = 'Todas las paradas verificadas';",
"  } else if (worst < PARTIAL_THRESHOLD) {",
"    level = 'parcial';",
"    label = 'Algunas paradas no se pudieron verificar';",
"  } else {",
"    level = 'no_verificada';",
"    label = 'No se pudo verificar la mayoria del recorrido';",
"  }",
"  return { level: level, label: label, worstRatio: worst, totalDegraded: totalDeg };",
"}",
"",
].join('\n');

const HONESTY_TEST = [
"// tests/test_honesty.mjs",
"import { computeHonestyAssessment, ratioFor, PARTIAL_THRESHOLD } from './_honesty_impl.mjs';",
"",
"let pass = 0, fail = 0;",
"const failures = [];",
"function eq(name, actual, expected) {",
"  const a = JSON.stringify(actual), e = JSON.stringify(expected);",
"  if (a === e) { pass++; console.log('  \u2713', name); }",
"  else { fail++; failures.push({ name, actual: a, expected: e }); console.log('  \u2717', name, '\\n      actual:', a, '\\n      expected:', e); }",
"}",
"function tru(name, cond, hint) {",
"  if (cond) { pass++; console.log('  \u2713', name); }",
"  else { fail++; failures.push({ name, hint }); console.log('  \u2717', name, hint ? '(' + hint + ')' : ''); }",
"}",
"",
"console.log('ratioFor');",
"eq('no validation -> 0', ratioFor({}), 0);",
"eq('total 0 -> 0', ratioFor({ validation: { total: 0, degradedSteps: 0 } }), 0);",
"eq('2/4 -> 0.5', ratioFor({ validation: { total: 4, degradedSteps: 2 } }), 0.5);",
"eq('0/5 -> 0', ratioFor({ validation: { total: 5, degradedSteps: 0 } }), 0);",
"",
"console.log('computeHonestyAssessment');",
"eq('empty routes', computeHonestyAssessment([]).level, 'confiable');",
"eq('null routes', computeHonestyAssessment(null).level, 'confiable');",
"eq('all valid', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 0 } }, { validation: { total: 3, degradedSteps: 0 } }]).level, 'confiable');",
"eq('one bus degraded 1/5 -> parcial', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 1 } }]).level, 'parcial');",
"eq('boundary 2/5 -> parcial (strict)', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 2 } }]).level, 'parcial');",
"eq('3/5 -> no_verificada', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 3 } }]).level, 'no_verificada');",
"eq('mixed worst 60% -> no_verificada', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 0 } }, { validation: { total: 5, degradedSteps: 3 } }]).level, 'no_verificada');",
"eq('aggregate totalDegraded', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 2 } }, { validation: { total: 3, degradedSteps: 1 } }]).totalDegraded, 3);",
"tru('worstRatio is number', typeof computeHonestyAssessment([]).worstRatio === 'number', 'expected number');",
"tru('worstRatio in [0,1]', computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 3 } }]).worstRatio <= 1);",
"eq('missing validation field treated as 0', computeHonestyAssessment([{ steps: [] }]).level, 'confiable');",
"eq('total:0 treated as 0', computeHonestyAssessment([{ validation: { total: 0, degradedSteps: 5 } }]).level, 'confiable');",
"eq('non-empty Spanish label for confiable', /verificadas/.test(computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 0 } }]).label), true);",
"eq('non-empty Spanish label for parcial', /Algunas/.test(computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 1 } }]).label), true);",
"eq('non-empty Spanish label for no_verificada', /mayoria/.test(computeHonestyAssessment([{ validation: { total: 5, degradedSteps: 4 } }]).label), true);",
"eq('PARTIAL_THRESHOLD exported', PARTIAL_THRESHOLD, 0.40);",
"",
"console.log('\\n-----');",
"if (fail === 0) { console.log('ALL TESTS PASS (' + pass + '/' + (pass + fail) + ')'); process.exit(0); }",
"else { console.log('FAILED ' + fail + '/' + (pass + fail)); for (const f of failures) console.log(' -', f.name, JSON.stringify(f)); process.exit(1); }",
"",
].join('\n');

const TELEMETRY_IMPL = [
"// tests/_validatorTelemetry_impl.mjs",
"export const KEY = 'metrobot.validation.telemetry.v1';",
"export const CAP = 50;",
"",
"function isValidEntry(x) {",
"  return x && typeof x.ts === 'number' && typeof x.degraded === 'number' && typeof x.validated === 'number';",
"}",
"",
"export function loadTelemetry(storage) {",
"  if (!storage) return [];",
"  try {",
"    const raw = storage.getItem(KEY);",
"    if (!raw) return [];",
"    const v = JSON.parse(raw);",
"    return Array.isArray(v) ? v.filter(isValidEntry) : [];",
"  } catch (_e) { return []; }",
"}",
"",
"export function saveTelemetry(storage, sessions) {",
"  if (!storage) return false;",
"  try {",
"    const trimmed = sessions.slice(-CAP);",
"    storage.setItem(KEY, JSON.stringify(trimmed));",
"    return true;",
"  } catch (_e) { return false; }",
"}",
"",
"export function recordSession(storage, validated, degraded, now) {",
"  const sessions = loadTelemetry(storage);",
"  sessions.push({ ts: now || Date.now(), validated: validated, degraded: degraded });",
"  return saveTelemetry(storage, sessions);",
"}",
"",
"export function summarizeTelemetry(storage) {",
"  const sessions = loadTelemetry(storage);",
"  let totalValidated = 0;",
"  let totalDegraded = 0;",
"  for (const s of sessions) {",
"    totalValidated += s.validated || 0;",
"    totalDegraded += s.degraded || 0;",
"  }",
"  const total = totalValidated + totalDegraded;",
"  return { sessions: sessions.length, totalValidated: totalValidated, totalDegraded: totalDegraded, ratio: total === 0 ? 0 : totalDegraded / total };",
"}",
"",
].join('\n');

const TELEMETRY_TEST = [
"// tests/test_validatorTelemetry.mjs",
"import { loadTelemetry, saveTelemetry, recordSession, summarizeTelemetry, KEY, CAP } from './_validatorTelemetry_impl.mjs';",
"",
"let pass = 0, fail = 0;",
"const failures = [];",
"function eq(name, actual, expected) {",
"  const a = JSON.stringify(actual), e = JSON.stringify(expected);",
"  if (a === e) { pass++; console.log('  \u2713', name); }",
"  else { fail++; failures.push({ name, actual: a, expected: e }); console.log('  \u2717', name, '\\n      actual:', a, '\\n      expected:', e); }",
"}",
"function tru(name, cond, hint) {",
"  if (cond) { pass++; console.log('  \u2713', name); }",
"  else { fail++; failures.push({ name, hint }); console.log('  \u2717', name, hint ? '(' + hint + ')' : ''); }",
"}",
"",
"function fakeStorage() {",
"  const m = new Map();",
"  return { getItem: (k) => (m.has(k) ? m.get(k) : null), setItem: (k, v) => m.set(k, String(v)), removeItem: (k) => m.delete(k) };",
"}",
"",
"console.log('loadTelemetry');",
"eq('empty -> []', loadTelemetry(fakeStorage()), []);",
"eq('null storage -> []', loadTelemetry(null), []);",
"eq('corrupt JSON -> []', loadTelemetry({ getItem: () => 'not-json', setItem: () => {} }), []);",
"eq('schema drop -> []', loadTelemetry({ getItem: () => JSON.stringify([{ ts: 'no', validated: 1 }]), setItem: () => {} }), []);",
"",
"console.log('saveTelemetry');",
"eq('null storage -> false', saveTelemetry(null, []), false);",
"const s1 = fakeStorage();",
"eq('roundtrip ok', saveTelemetry(s1, [{ ts: 1, validated: 5, degraded: 0 }]), true);",
"eq('persisted', loadTelemetry(s1), [{ ts: 1, validated: 5, degraded: 0 }]);",
"",
"console.log('recordSession');",
"eq('null storage -> false', recordSession(null, 5, 1, 100), false);",
"const s2 = fakeStorage();",
"eq('record + load', recordSession(s2, 3, 1, 1000) && JSON.stringify(loadTelemetry(s2)), JSON.stringify([{ ts: 1000, validated: 3, degraded: 1 }]));",
"eq('cap behavior 60 -> 50', (function () { const s = fakeStorage(); for (let i = 0; i < 60; i++) recordSession(s, 1, 0, i); return loadTelemetry(s).length === 50; })(), true);",
"eq('cap keeps most recent', (function () { const s = fakeStorage(); for (let i = 0; i < 60; i++) recordSession(s, 1, 0, i); return loadTelemetry(s)[49].ts === 59; })(), true);",
"",
"console.log('summarizeTelemetry');",
"eq('empty', summarizeTelemetry(fakeStorage()).sessions, 0);",
"eq('empty ratio 0', summarizeTelemetry(fakeStorage()).ratio, 0);",
"const s3 = fakeStorage();",
"recordSession(s3, 4, 1, 100);",
"recordSession(s3, 2, 2, 200);",
"eq('mixed totals', summarizeTelemetry(s3).totalValidated, 6);",
"eq('mixed degraded', summarizeTelemetry(s3).totalDegraded, 3);",
"eq('mixed ratio', summarizeTelemetry(s3).ratio, 0.5);",
"eq('mixed sessions count', summarizeTelemetry(s3).sessions, 2);",
"",
"console.log('\\n-----');",
"if (fail === 0) { console.log('ALL TESTS PASS (' + pass + '/' + (pass + fail) + ')'); process.exit(0); }",
"else { console.log('FAILED ' + fail + '/' + (pass + fail)); for (const f of failures) console.log(' -', f.name, JSON.stringify(f)); process.exit(1); }",
"",
].join('\n');

const EVIDENCE_IMPL = [
"// tests/_evidence_impl.mjs",
"export function computeEvidenceScore(route) {",
"  if (!route || !Array.isArray(route.steps)) return 0;",
"  let total = 0;",
"  let scored = 0;",
"  for (const s of route.steps) {",
"    if (s.mode !== 'bus_articulado') continue;",
"    total++;",
"    const ev = s._evidence;",
"    if (ev && ev.sourceRouteId && ev.sourceStopName) scored++;",
"  }",
"  if (total === 0) return 1;",
"  return scored / total;",
"}",
"",
"export function missingEvidence(route) {",
"  if (!route || !Array.isArray(route.steps)) return [];",
"  const out = [];",
"  for (const s of route.steps) {",
"    if (s.mode !== 'bus_articulado') continue;",
"    const ev = s._evidence;",
"    if (!(ev && ev.sourceRouteId && ev.sourceStopName)) {",
"      out.push(s.instruction || s.mode || 'bus_articulado');",
"    }",
"  }",
"  return out;",
"}",
"",
].join('\n');

const EVIDENCE_TEST = [
"// tests/test_evidence.mjs",
"import { computeEvidenceScore, missingEvidence } from './_evidence_impl.mjs';",
"",
"let pass = 0, fail = 0;",
"const failures = [];",
"function eq(name, actual, expected) {",
"  const a = JSON.stringify(actual), e = JSON.stringify(expected);",
"  if (a === e) { pass++; console.log('  \u2713', name); }",
"  else { fail++; failures.push({ name, actual: a, expected: e }); console.log('  \u2717', name, '\\n      actual:', a, '\\n      expected:', e); }",
"}",
"",
"console.log('computeEvidenceScore');",
"eq('no bus steps -> 1', computeEvidenceScore({ steps: [{ mode: 'metro' }] }), 1);",
"eq('2 bus both with evidence -> 1', computeEvidenceScore({ steps: [{ mode: 'bus_articulado', _evidence: { sourceRouteId: 'C7-001', sourceStopName: 'Niquia' } }, { mode: 'bus_articulado', _evidence: { sourceRouteId: '142I', sourceStopName: 'Sur' } }] }), 1);",
"eq('2 bus one with evidence -> 0.5', computeEvidenceScore({ steps: [{ mode: 'bus_articulado', _evidence: { sourceRouteId: 'C7-001', sourceStopName: 'Niquia' } }, { mode: 'bus_articulado' }] }), 0.5);",
"eq('2 bus no evidence -> 0', computeEvidenceScore({ steps: [{ mode: 'bus_articulado' }, { mode: 'bus_articulado' }] }), 0);",
"eq('empty route -> 0', computeEvidenceScore({}), 0);",
"eq('null route -> 0', computeEvidenceScore(null), 0);",
"eq('incomplete _evidence -> 0', computeEvidenceScore({ steps: [{ mode: 'bus_articulado', _evidence: { sourceRouteId: 'X' } }, { mode: 'bus_articulado', _evidence: { sourceStopName: 'Y' } }] }), 0);",
"",
"console.log('missingEvidence');",
"eq('returns instruction strings', missingEvidence({ steps: [{ mode: 'bus_articulado', instruction: 'Toma C7-001' }, { mode: 'bus_articulado', _evidence: { sourceRouteId: '142I', sourceStopName: 'Sur' } }] }), ['Toma C7-001']);",
"eq('empty route -> []', missingEvidence({}), []);",
"eq('null route -> []', missingEvidence(null), []);",
"",
"console.log('\\n-----');",
"if (fail === 0) { console.log('ALL TESTS PASS (' + pass + '/' + (pass + fail) + ')'); process.exit(0); }",
"else { console.log('FAILED ' + fail + '/' + (pass + fail)); for (const f of failures) console.log(' -', f.name, JSON.stringify(f)); process.exit(1); }",
"",
].join('\n');

write('tests/_honesty_impl.mjs', HONESTY_IMPL);
write('tests/test_honesty.mjs', HONESTY_TEST);
write('tests/_validatorTelemetry_impl.mjs', TELEMETRY_IMPL);
write('tests/test_validatorTelemetry.mjs', TELEMETRY_TEST);
write('tests/_evidence_impl.mjs', EVIDENCE_IMPL);
write('tests/test_evidence.mjs', EVIDENCE_TEST);
