const fs = require('fs');
const IMPL = [
"// tests/_sheet_drag_impl.mjs",
"// Pure logic for useSheetDrag. Decides the next snap index given current snap,",
"// drag delta (px) and release velocity (px/ms). No DOM, no React.",
"",
"const DRAG_THRESHOLD = 8;",
"const VELOCITY_THRESHOLD = 0.3;",
"const MIN_DELTA = 4;",
"",
"export function nextSnap(currentSnap, snapPoints, deltaY, velocityY) {",
"  if (!Array.isArray(snapPoints) || snapPoints.length === 0) return 0;",
"  const max = snapPoints.length - 1;",
"  const cur = Math.max(0, Math.min(max, currentSnap | 0));",
"  const d = typeof deltaY === 'number' ? deltaY : 0;",
"  const v = typeof velocityY === 'number' ? velocityY : 0;",
"  if (Math.abs(d) < MIN_DELTA && Math.abs(v) < VELOCITY_THRESHOLD) return cur;",
"  let next = cur;",
"  if (d < -DRAG_THRESHOLD || v < -VELOCITY_THRESHOLD) {",
"    next = cur + 1;",
"  } else if (d > DRAG_THRESHOLD || v > VELOCITY_THRESHOLD) {",
"    next = cur - 1;",
"  }",
"  return Math.max(0, Math.min(max, next));",
"}",
"",
].join('\n');
const TEST = [
"// tests/test_sheet_drag.mjs",
"import { nextSnap } from './_sheet_drag_impl.mjs';",
"",
"const SNAPS = [72, 320, 720];",
"",
"let pass = 0, fail = 0;",
"const failures = [];",
"function eq(name, actual, expected) {",
"  const a = JSON.stringify(actual), e = JSON.stringify(expected);",
"  if (a === e) { pass++; console.log('  \u2713', name); }",
"  else { fail++; failures.push({ name, actual: a, expected: e }); console.log('  \u2717', name, '\\n      actual:', a, '\\n      expected:', e); }",
"}",
"",
"console.log('nextSnap');",
"eq('empty snaps -> 0', nextSnap(1, [], 0, 0), 0);",
"eq('no drag -> same', nextSnap(1, SNAPS, 0, 0), 1);",
"eq('tiny drag 2px -> same', nextSnap(1, SNAPS, 2, 0), 1);",
"eq('drag UP 200px from mid -> max', nextSnap(1, SNAPS, -200, 0), 2);",
"eq('drag DOWN 200px from max -> mid', nextSnap(2, SNAPS, 200, 0), 1);",
"eq('drag DOWN 600px from mid -> min', nextSnap(1, SNAPS, 600, 0), 0);",
"eq('fast flick DOWN v=0.8 from mid -> min', nextSnap(1, SNAPS, 0, 0.8), 0);",
"eq('fast flick UP v=-0.8 from min -> max', nextSnap(0, SNAPS, 0, -0.8), 2);",
"eq('at min, drag DOWN -> min', nextSnap(0, SNAPS, 600, 0), 0);",
"eq('at max, drag UP -> max', nextSnap(2, SNAPS, -600, 0), 2);",
"eq('boundary clamping at min', nextSnap(-5, SNAPS, 600, 0), 0);",
"eq('boundary clamping at max', nextSnap(99, SNAPS, -600, 0), 2);",
"eq('mixed velocity+delta both negative -> up', nextSnap(1, SNAPS, -10, -0.5), 2);",
"eq('mixed velocity+delta both positive -> down', nextSnap(1, SNAPS, 10, 0.5), 0);",
"eq('just under threshold no snap', nextSnap(1, SNAPS, 7, 0), 1);",
"eq('at 8px exactly snaps up', nextSnap(1, SNAPS, -8, 0), 2);",
"",
"console.log('\\n-----');",
"if (fail === 0) { console.log('ALL TESTS PASS (' + pass + '/' + (pass + fail) + ')'); process.exit(0); }",
"else { console.log('FAILED ' + fail + '/' + (pass + fail)); for (const f of failures) console.log(' -', f.name, JSON.stringify(f)); process.exit(1); }",
"",
].join('\n');
fs.writeFileSync('tests/_sheet_drag_impl.mjs', IMPL, 'utf8');
fs.writeFileSync('tests/test_sheet_drag.mjs', TEST, 'utf8');
console.log('wrote', IMPL.length, TEST.length);
